version: '3'
name: linguacafe

networks:
    linguacafe:
        driver: bridge

services:
    webserver:
        container_name: linguacafe-webserver
        # https://docs.docker.com/compose/compose-file/build/#illustrative-example
        image: ghcr.io/simjanos-dev/linguacafe-webserver:main
        build:
            context: .
            dockerfile: ./docker/PhpDockerfile
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./storage/app:/var/www/html/storage/app
            - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "9191:80"
            - "3000:3000"
        networks:
            - linguacafe
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        ports:
          - "3308:3306"
        volumes:
          - ./docker/mysql:/var/lib/mysql
        environment:
          MYSQL_DATABASE: linguacafe
          MYSQL_USER: linguacafe
          MYSQL_PASSWORD: linguacafe
          MYSQL_ROOT_PASSWORD: linguacafe
          SERVICE_NAME: linguacafe
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 3
        networks:
            - linguacafe
    python:
        container_name: linguacafe-python-service
        command: /app/manage.py runserver 0.0.0.0:8678
        restart: unless-stopped
        tty: true
        # https://docs.docker.com/compose/compose-file/build/#illustrative-example
        image: ghcr.io/simjanos-dev/linguacafe-python-service:main
        build:
            dockerfile: ./docker/PythonDockerfile
        volumes:
            - ./tools/django_server:/app
            - ./storage/app:/var/www/html/storage/app
        networks:
            - linguacafe
    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        user: 1000:1000
        volumes:
            - /your/path/to/config:/config
            - /your/path/to/cache:/cache
            - /your/path/to/media:/media:ro
        restart: 'unless-stopped'
        ports:
            - 8096:8096
        networks:
            - linguacafe
