version: "3"
name: linguacafe

networks:
    linguacafe:
        driver: bridge

services:
    webserver:
        image: ghcr.io/simjanos-dev/linguacafe-webserver:main
        container_name: linguacafe-webserver
        depends_on:
            mysql
        volumes:
            - /your/linguacafe/dict/folder:/var/www/html/storage/app/dictionaries
            - /your/linguacafe/logs/folder:/var/www/html/storage/logs
            - /your/linguacafe/temp/folder:/var/www/html/storage/app/temp
        ports:
            - "9191:80"
            - "3000:3000"
        networks:
            - linguacafe
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        volumes:
            - /your/linguacafe/database/folder:/var/lib/mysql
        environment:
            MYSQL_DATABASE: linguacafe
            MYSQL_USER: linguacafe
            MYSQL_PASSWORD: linguacafe
            MYSQL_ROOT_PASSWORD: linguacafe
            SERVICE_NAME: linguacafe
        command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
        networks:
            - linguacafe
    python:
        container_name: linguacafe-python-service
        command: /app/manage.py runserver 0.0.0.0:8678
        restart: unless-stopped
        tty: true
        image: ghcr.io/simjanos-dev/linguacafe-python-service:main
        volumes:
            - /your/linguacafe/dict/folder:/var/www/html/storage/app/dictionaries
            - /your/linguacafe/temp/folder:/var/www/html/storage/app/temp
        networks:
            - linguacafe
        # platform: linux/amd64
